Rewrite the exception handling tutorial
fpco/haskell.fpcomplete.com pull request #11
Opened 2019-03-11 13:52 UTC by snoyberg

2019-03-11 16:42 UTC, psibi requested changes
Apart from some minor comments, this looks excellent!

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +Instead of use the `Control.Exception` module, we recommend using the
/s/use/using ?

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +exceptions. What should the expected behavior here be?
> Instead, with asynchronous exceptions, we're allowed to clean up, but not recover. 

Is this the best practice or does the Haskell runtime itself doesn't allow us to recover ? Clarifying that would be helpful IMO.

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +```
Probably the code can be made more easy to (lazy) readers like me by using these constants:

```
oneMinute :: Int
oneMinute = 1000000

fiveMinute :: Int
fiveMinute = 5000000
```

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +cleanup call to occur an then immediately exit. This ensures that
/s/an/and ?

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +safeguards in place to ensure this happens; please see the "Async
/s/this/this doesn't ?

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
Probably it's useful to add here that it throws an exception of type `StringException` ?

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +We can also create hiearchies of exceptions. In my experience, these
/s/hiearchies/hierarchies

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +types. That's why, in our hiearchical exception above, I turned on
/s/hiearchical/hierarchical

2019-03-11 16:42 UTC, psibi commented on content/tutorials/exceptions.md
> +  unusal thing to do.)
/s/unusal/unusual

2019-03-12 03:51 UTC, snoyberg commented
Thanks for the thorough review! I've made updates to address all comments. I've left two discussions unresolved. Can you check that my edits address these points sufficiently?

2019-03-12 04:26 UTC, psibi approved these changes

2019-03-12 04:28 UTC, psibi commented
@snoyberg Thanks, I have resolved them. 

In the above documentation you have mentioned that `UnliftIO.Exception` is exported under `rio`. But I wasn't able to find any via hoogle:

https://www.stackage.org/lts-13.12/hoogle?q=try&package=rio

(even other hoogle queries like `SomeAsyncException`)

Am I doing something wrong ?

2019-03-12 05:00 UTC, snoyberg commented
I've reworded slightly to state this correctly: the _contents_ of that module are reexported under the `RIO` module. Thanks for pointing that out, and for the overall review!

2019-03-12 05:00 UTC, merged